# Header
menu:
  # 主页: /
  所有文章: /archives/index.html
  亲测: /tags/亲测/index.html
  前端: /tags/前端/index.html
  Tips: /tags/tips/index.html
  笔记: /tags/笔记/index.html
  # 我男神的地儿: http://www.sunxichen.com
  # 相册: http://nuomixin.com/instagram/

# SubNav
subnav:
  github: "https://github.com/trytuorisfy"
  weibo: "http://weibo.com/1933249531"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  mail: "mailto:tuorisfy@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: false
mathjax: false

# 是否开启动画效果
animate: false

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
#google_analytics: ''
baidu_tongji: true
favicon: "http://7sbkqu.com1.z0.glb.clouddn.com/favicon.png"

#你的头像url
avatar: "http://7sbkqu.com1.z0.glb.clouddn.com/avatar.jpg"
#是否开启分享
share: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
#6、Valine https://valine.js.org
# valine: 
#  appid:  iQD3W24cfvu1WB82GuUFQoVc-gzGzoHsz #Leancloud应用的appId
#  appkey:  nOw3zLema3nK8AjxW5OlajW1 #Leancloud应用的appKey
#  verify: false #验证码
#  notify: false #评论回复提醒
#  avatar: mm #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
 #placeholder: Just go go #评论框占位符
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
# friends: false
#开启——
friends:
  我男神的博客: http://www.sunxichen.com
  #卡卡的美丽传说: http://localhost:4000/
  #本泽马的博客: http://localhost:4000/
  #吉格斯的博客: http://localhost:4000/
  #习大大大不同: http://localhost:4000/
  #托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 无可救药的声控斯基